version: 2

jobs:
  test:
    docker:
      - image: python:3.7
      - image: circleci/redis:5.0
    steps:
      - checkout
      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - asyncio-redis-v1-{{ checksum "poetry.lock" }}
      - run:
          name: install dependencies
          command: |
            # Use our new PATH so we can call poetry from bash
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
            command -v poetry || python -m pip install --user poetry==0.12.12
            poetry install
      - save_cache:
          paths:
            - ./bot/.mypy_cache
            - /root/.cache/
          key: asyncio-redis-v1-{{ checksum "poetry.lock" }}
      - run:
          name: run tests
          command: ./s/test

  lint:
    docker:
      - image: python:3.7
    steps:
      - checkout
      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - asyncio-redis-v1-{{ checksum "poetry.lock" }}
      - run:
          name: install dependencies
          command: |
            # Use our new PATH so we can call poetry from bash
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
            command -v poetry || python -m pip install --user poetry==0.12.12
            poetry install
      - save_cache:
          paths:
            - ./bot/.mypy_cache
            - /root/.cache/
          key: asyncio-redis-v1-{{ checksum "poetry.lock" }}
      - run:
          name: run lints
          command: ./s/lint

  shellcheck:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get update
            apt-get install -y git shellcheck
      - run:
          name: run shellcheck
          command: |
            ./s/shellcheck

workflows:
  version: 2
  all:
    jobs:
      - shellcheck
  bot:
    jobs:
      - test
      - lint
